#!/bin/bash

##convert -resize 1000x1

Xaxis=$(export DISPLAY=:0;xrandr --current | grep '*' | uniq | awk '{print $1}' |  cut -d 'x' -f1)
Yaxis=$(export DISPLAY=:0;xrandr --current | grep '*' | uniq | awk '{print $1}' |  cut -d 'x' -f2)
MaxRes=$(($Xaxis-5))"x"$(($Yaxis-25))

for i in /home/tv/Downloads/*.JPG; do 
    echo "${i%.JPG} --- $MaxRes..."
    convert -resize $MaxRes -quality 90 $i ${i%.JPG}-klein.jpg
done
