#!/bin/bash

##convert -resize 1000x1

Xaxis=$(export DISPLAY=:0;xrandr --current | grep '*' | uniq | awk '{print $1}' |  cut -d 'x' -f1 | tail -n 1)
Yaxis=$(export DISPLAY=:0;xrandr --current | grep '*' | uniq | awk '{print $1}' |  cut -d 'x' -f2 | tail -n 1)
MaxRes=$(($Xaxis-5))"x"$(($Yaxis-25))

if [ $1 ];then
    DIR=$1
else
    DIR=/home/tv/content/photo
fi

rm -f $DIR/playlist.m3u

for i in $DIR/*.JPG; do 
    echo "${i%.JPG} --- $MaxRes..."
    convert -resize $MaxRes -quality 100 $i ${i%.JPG}-klein.jpg
    echo "${i%.JPG}-klein.jpg" >> $DIR/playlist.m3u
done
