#!/bin/bash

SET_NO_SOUND=--noaudio
#SET_NO_SOUND=""


killall -w -9 vlc

if [ $1 ];then
    export DISPLAY=:0 && vlc vlc --autoscale --no-video-title-show $SET_NO_SOUND --loop --fullscreen  $1 2> /dev/null &
else
  export DISPLAY=:0 && vlc --autoscale --no-video-title-show $SET_NO_SOUND --loop --fullscreen /tools/epam.m3u 2> /dev/null &
fi
